# Generated by Django 4.2.4 on 2023-08-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default='351447a1229041e68eaf33653a1f5504', editable=False, primary_key=True, serialize=False),
        ),
    ]
