# Generated by Django 4.2.4 on 2023-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default='f7dfc4645a8c495bb6b15400256d09b6', editable=False, primary_key=True, serialize=False),
        ),
    ]
