# Generated by Django 4.2.4 on 2023-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default='5f0a6c43af9e447c8a1ea49bb053676e', editable=False, primary_key=True, serialize=False),
        ),
    ]
